language: php

php:
  - 5.6
  - 7.0

before_script:
  - mkdir bootstrap/cache
  - mkdir storage
  - mkdir storage/app
  - mkdir storage/framework
  - mkdir storage/framework/sessions
  - mkdir storage/framework/cache
  - mkdir storage/framework/views
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit